// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace TreenodeCssNamespace {
    export interface ITreenodeCss {
        children: string;
        description: string;
        error: string;
        name: string;
        node: string;
        selected: string;
    }
}

declare const TreenodeCssModule: TreenodeCssNamespace.ITreenodeCss;

export = TreenodeCssModule;
